### ISSUE TITLE
undefined method `name' for #<Puppet::Util::Execution::ProcessOutput

### ISSUE THREAD

**Issue by igalic** [Brainsware/puppet-s3ql#1]
with the following mount-point existing,

``` console
igalic@levix ~/s/p/s3ql (master=)> mount | grep fuse.s3ql
gs://fluffy/levix on /home/igalic/src/bw/kobe type fuse.s3ql (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

when i run `puppet resource s3ql_mount --debug --trace` i get the following error:

```
igalic@levix ~/s/p/s3ql (master=)> puppet resource s3ql_mount --debug --trace
Debug: Runtime environment: puppet_version=4.2.2, ruby_version=2.1.6, run_mode=user, default_encoding=UTF-8
Debug: Executing: '/bin/mount'
Error: Could not run: undefined method `name' for #<Puppet::Util::Execution::ProcessOutput:0x000000033798a0>
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1146:in `block (2 levels) in instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1143:in `collect'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1143:in `block in instances'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1136:in `collect'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1136:in `instances'
/opt/puppetlabs/puppet/lib/ruby/gems/2.1.0/gems/puppet-4.2.1/lib/puppet/indirector/resource/ral.rb:24:in `search'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:260:in `search'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:225:in `find_or_save_resources'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/resource.rb:140:in `main'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:352:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:446:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:128:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
igalic@levix ~/s/p/s3ql (master=) [1]> 
```

**Comment by ffrank** [comment]
I'd start by adding debug output around [this line](https://github.com/Brainsware/puppet-s3ql/blob/master/lib/puppet/provider/s3ql_mount/s3ql_mount.rb#L29).

**Comment by igalic** [comment]
here we go:

```
igalic@levix ~/s/p/s3ql (master ⚡=) [1]> puppet resource s3ql_mount --debug --trace
Debug: Runtime environment: puppet_version=4.2.2, ruby_version=2.1.6, run_mode=user, default_encoding=UTF-8
Debug: Executing: '/bin/mount'

From: /home/igalic/.puppetlabs/etc/code/environments/production/modules/s3ql/lib/puppet/provider/s3ql_mount/s3ql_mount.rb @ line 30 s3ql_mount.instances:

    26: def self.instances
    27:   mounts = mount.split("\n").select { |line| line.include? "fuse.s3ql" }
    28:   mounts.each do |mnt|
    29:     storage_url, _, mountpoint, _, _, options = mnt.split
 => 30:     require 'pry' ; binding.pry
    31:     # and initialize @property_hash
    32:     new( :name        => mountpoint,
    33:          :mountpoint  => mountpoint,
    34:          :storage_url => storage_url,
    35:          :owner       => options.sub(/.*user_id=(\d+).*/, '\1'),
    36:          :group       => options.sub(/.*group_id=(\d+).*/, '\1'),
    37:          :backend     => storage_url.split(':')[0]
    38:        )
    39:   end
    40: end

[1] pry(s3ql_mount)> storage_url
=> "gs://fluffy/levix"
[2] pry(s3ql_mount)> mountpoint
=> "/home/igalic/src/bw/kobe"
[3] pry(s3ql_mount)> options
=> "(rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)"
[4] pry(s3ql_mount)> 
```

**Comment by igalic** [comment]
or better yet:

```
[1] pry(s3ql_mount)> play -l 31-38
=> (provider=s3ql_mount)
[2] pry(s3ql_mount)> cd _
[3] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> ls
Puppet::Util::Errors#methods: adderrorcontext  devfail  error_context  exceptwrap  fail
Comparable#methods: <  <=  ==  >  >=  between?
Puppet::Provider#methods: 
  <=>  alert  clear  command  crit  debug  emerg  err  execfail  execpipe  execute  get  info  inspect  name  notice  resource  resource=  set  to_s  warning
Puppet::Type::S3ql_mount::FeatureModule#methods: feature?  features  has_feature  has_features  satisfies?
s3ql_mount#methods: 
  backend   backend_login   backend_options   backend_password   fs_passphrase   group   mount       mountpoint=  owner=    provider=  storage_url   umount
  backend=  backend_login=  backend_options=  backend_password=  fs_passphrase=  group=  mountpoint  owner        provider  s3ql       storage_url=
self.methods: __pry__
instance variables: @property_hash
locals: _  __  _dir_  _ex_  _file_  _in_  _out_  _pry_
[4] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> name
=> "/home/igalic/src/bw/kobe"
[5] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> mountpoint
=> "/home/igalic/src/bw/kobe"
[6] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> storage_url
=> "gs://fluffy/levix"
[7] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> owner
=> "1000"
[8] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> group
=> "1000"
[9] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> backend
=> "gs"
[10] pry(#<Puppet::Type::S3ql_mount::ProviderS3ql_mount>):1> 
```

**Comment by igalic** [comment]
should i be confused about this?

```
igalic@levix ~/s/p/s3ql (master ⚡=) [1]> puppet resource s3ql_mount --debug --trace
Debug: Runtime environment: puppet_version=4.2.2, ruby_version=2.1.6, run_mode=user, default_encoding=UTF-8
Debug: Executing: '/bin/mount'

From: /home/igalic/.puppetlabs/etc/code/environments/production/modules/s3ql/lib/puppet/provider/s3ql_mount/s3ql_mount.rb @ line 39 s3ql_mount.instances:

    26: def self.instances
    27:   mounts = mount.split("\n").select { |line| line.include? "fuse.s3ql" }
    28:   p_h = mounts.each do |mnt|
    29:     storage_url, _, mountpoint, _, _, options = mnt.split
    30:     # and initialize @property_hash
    31:     new( :name        => mountpoint,
    32:          :mountpoint  => mountpoint,
    33:          :storage_url => storage_url,
    34:          :owner       => options.sub(/.*user_id=(\d+).*/, '\1'),
    35:          :group       => options.sub(/.*group_id=(\d+).*/, '\1'),
    36:          :backend     => storage_url.split(':')[0]
    37:        )
    38:   end
 => 39:   require 'pry' ; binding.pry
    40: end

[1] pry(s3ql_mount)> p_h
=> ["gs://fluffy/levix on /home/igalic/src/bw/kobe type fuse.s3ql (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)"]
[2] pry(s3ql_mount)> 
```

**Comment by ffrank** [comment]
I believe you want to `collect` instead of `each` here. That might be all there is to it.

Good catch, confusion notwithstanding!

**Comment by igalic** [comment]
duh. thank you so much @ffrank
